export const AUTHENTICATE_RIDER="AUTHENTICATE_RIDER";
export const PASSWORD_CHANGED="PASSWORD_CHANGED";


//Request related Types starts here.....
export const REFRESH_REQUEST_STATUS="REFRESHREQUESTSTATUS";
export const SET_AVAILABLE_TRUE="SETAVAILABLETRUE";
export const SET_AVAILABLE_FALSE="SETAVAILABLEFALSE";
export const RIDER_REQUEST_COME="RIDEREQUESTCOME";
export const RIDE_ACCEPT_TIME_OVER="RIDEACCEPTTIMEOVER";
export const SET_BUFFERING_CODE="SETBUFFERRINGCODE";
export const SET_TRIP_ONE="SETTRIPONE";
export const SET_TRIP_TWO="SETTRIPTWO";
export const SET_GEN_BUFFERRING="SETGENBUFFERRING";
export const END_GEN_BUFFERRING="ENDGENBUFFERRING";

export const SET_GEN_COMPLETE_REQUEST="SETGENCOMPLETEREQUEST";
export const SET_SECURITY_CODE="SETSECURITYCODE";

//Geolocation related types starts here.....
export const SET_MY_LOCATION="SETMYLOCATION";

